config/routes.rb
Rails.application.routes.draw do
  get :health_check, to: 'health_check#health_check'
  root to: 'articles#index'
  devise_for :users
  resources :articles do
    resources :comments
  end
  get 'photos', to: 'images#index'
  get 'photos', to: 'photos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # connects_to database: :primary
  # connects_to database: { writing: :primary, reading: :primary }
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :public_comments, -> { where is_public: true }, class_name: 'Comment'

  validates :title, presence: true
  validates :content, presence: true

  scope :recent, -> { where("created_at > '#{3.days.ago}'") }
  scope :public_articles, -> { where(is_public: true) }

  enum priority: {
    important: 10,
    normal: 20,
    light: 30
  }

  def self.public_articles
    where(is_public: true) if false
  end

  def commented_by?(user)
    comments.pluck(:user_id).include?(user.id)
  end

  def self.sort_by_comment_count_before
    self
      .includes(:comments)
      .select('*', "(SELECT COUNT(comments.id) FROM comments WHERE articles.id = comments.article_id AND created_at > '#{30.days.ago}' AND comments.is_public = TRUE) AS comment_count")
      .order(comment_count: :desc)
  end

  # SELECT *, (SELECT COUNT(comments.id) FROM comments WHERE articles.id = comments.article_id) AS comment_count FROM `articles` ORDER BY `comment_count` DESC

  # fromメソッドで書いてみる
  def self.sort_by_comment_count_after
    self
      .includes(:comments)
      .from(Comment.where('articles.id = comments.article_id').default_comments, :subquery)
      .order(comment_count: :desc)
  end
end



# MEMO
# Topic.select('title').from(Topic.approved)

# SELECT title FROM (SELECT * FROM topics WHERE approved = 't') subquery

# Topic.select('a.title').from(Topic.approved, :a)
# SELECT a.title FROM (SELECT * FROM topics WHERE approved = 't') a

# SELECT *, (SELECT COUNT(comments.id) FROM comments WHERE articles.id = comments.article_id) AS comment_count FROM `articles` ORDER BY `comment_count` DESC
# Comment.count.from(Comment.where('articles.id = comments.article_id').default_comments)

# 正規のSQL
# "SELECT *, (SELECT COUNT(comments.id) FROM comments WHERE articles.id = comments.article_id) AS comment_count FROM `articles` ORDER BY `comment_count` DESC"
# "SELECT *, COUNT(subquery.id) comment_count FROM (SELECT `comments`.* FROM `comments` WHERE (articles.id = comments.article_id) AND (created_at > '2022-04-02 08:56:33 +0900') AND `comments`.`is_public` = TRUE) subquery ORDER BY `comment_count` DESC"

# (SELECT COUNT(comments.id) FROM comments WHERE articles.id = comments.article_id)

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  scope :recent, -> { where("created_at > '#{30.days.ago}'") }
  scope :public_comments, -> { where(is_public: true) }
  scope :default_comments, -> { recent.public_comments }

  def is_comment_by?(user)
    user_id == user.id
  end
end

app/models/seconds_record.rb
class SecondaryRecord < ActiveRecord::Base
  self.abstract_class = true

  # connects_to database: { writing: :secondary, reading: :secondary }
  # connects_to database: :secondary
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AjaxErrorRenderer
end

app/controllers/articles_controller.rb
require 'prawn'

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  # layout 'special_articles'

  # GET /articles or /articles.json
  def index
    @articles = Article.all.order(Arel.sql('priority IS NULL ASC, priority ASC'))
    # @articles = Article.all.order(Arel.sql('priority IS NULL ASC, priority ASC'))
    # @articles = Article.all.order(Arel.sql('CASE WHEN priority IS NULL THEN 1 ELSE 0 END, priority ASC'))
    # @articles = Article.all.order(Arel.sql('ifnull(priority, 2147483647) ASC'))

    # @articles = Comment
    #   .default_comments
    #   .group(:article_id)
    #   .includes(:article)
    #   .select(:article_id, 'count(*) as c')
    #   .order(c: :desc)
    #   .map{_1.article}
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments

    @html = "#{@article.title}"
  end

  # GET /articles/new
  def new
    @article = Article.new
    # redirect_back(fallback_location: root_path)
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: "Article was successfully created."
      user = User.last
      ArticleMailer.with(user: user).notice.deliver_later
      # puts message
      # sleep 10
      # ArticleMailer.with(user: User.last).notice.deliver_later
    else
      render_ajax_error model: @article
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end

    def download_pdf
      send_data generate_pdf,
                filename: "test.pdf",
                type: "application/pdf"
    end

    def generate_pdf
      Prawn::Document.new do
        text 'test', align: :center
        text "Address: Tokyo"
        text "Email: test@example.com"
      end.render
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    comment = @article.comments.build(content: params[:content], user: User.first)
    comment.save
    redirect_to article_path(@article)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    render plain: 'ImagesController'
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    render plain: 'PhotosController'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% user = User.first %>
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.content %></td>
      <td><%= article.priority %></td>
      <td><%= link_to 'Show', article %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<!--
<% user = User.first %>
<div class="container">
  <% @comments.each do |comment| %>
    <p>
      <%= comment.content %>
      <%= comment.is_comment_by?(user) ? '✓' : '✗' %>
    </p>
  <% end %>
</div>
-->

<%= form_with model: @comment, url: article_comments_path(@article), method: :post do |f| %>
  <%= f.text_field :content %>
  <%= f.submit 'コメントする' %>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<br>
<%= raw @html %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/special_articles.html.erb
<h1>layouts/articles.html.erbのビュー</h1>